name: Run Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - '1.x'
      - '2.x'

jobs:
  tests:
    name: PHP ${{ matrix.php-versions }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '8.1', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, gmp, sqlite, mbstring
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-versions }}-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer test
